import type { DashboardData } from "./types";

export const fixtureDashboardData: DashboardData = {
  health: {
    status: "fixture",
    service: "agentx-kernel-api",
    checked_at: "2026-06-18T09:00:00+05:30",
  },
  overview: {
    system_state: "live-dogfood",
    active_instances: 3,
    active_runs: 4,
    parked_runs: 2,
    approvals_waiting: 3,
    manual_queue_depth: 5,
    ledger_events_today: 47,
    automation_coverage: 0.68,
    monthly_net: 1840,
    gateway_health: "credential-boundary-enforced",
    ring_mix: {
      observe: 1,
      assist: 2,
      autopilot: 0,
    },
    last_commit_at: "2026-06-18T08:54:30+05:30",
  },
  instances: [
    {
      id: "inst-kaveri",
      name: "Kaveri Pumps",
      business: "Industrial pump distributor",
      mandate_type: "indian_b2b_lead_finder",
      ring: "assist",
      trust_score: 82,
      state: "live",
      health: "green",
      owner: "Ops / Mrigesh",
      monthly_net: 920,
      facts: [
        {
          id: "fact-kav-1",
          label: "Primary ICP",
          value: "Plant maintenance heads at food-processing units in Gujarat",
          confidence: 0.84,
          provenance: "run-172/firecrawl/company-page",
          source: "Firecrawl",
          committed_at: "2026-06-18T08:41:00+05:30",
        },
        {
          id: "fact-kav-2",
          label: "Sender of record",
          value: "sales@kaveripumps.example",
          confidence: 0.91,
          provenance: "manager-action-approve-29",
          source: "Manager approval",
          committed_at: "2026-06-18T08:45:12+05:30",
        },
        {
          id: "fact-kav-3",
          label: "Do-not-contact",
          value: "No WhatsApp or voice automation in Phase 1",
          confidence: 1,
          provenance: "policy/invariant-6",
          source: "Kernel policy",
          committed_at: "2026-06-18T08:52:03+05:30",
        },
      ],
      ring_history: [
        {
          at: "2026-06-17T19:20:00+05:30",
          ring: "observe",
          actor: "operator",
          reason: "new instance created",
        },
        {
          at: "2026-06-18T07:50:00+05:30",
          ring: "assist",
          actor: "operator",
          reason: "two human-reviewed lead batches passed",
        },
      ],
      trust_history: [
        { label: "source match", score: 88, delta: 6 },
        { label: "draft quality", score: 76, delta: 2 },
        { label: "manual corrections", score: 91, delta: 9 },
      ],
      threads: [
        {
          id: "thread-kav-1",
          channel: "email",
          subject: "Batch 12 draft outreach",
          state: "waiting approval",
          updated_at: "2026-06-18T08:46:00+05:30",
        },
        {
          id: "thread-kav-2",
          channel: "manual",
          subject: "ICP correction from owner",
          state: "settled",
          updated_at: "2026-06-18T07:30:00+05:30",
        },
      ],
      pnl: {
        revenue: 1200,
        cost: 280,
        margin: 920,
      },
    },
    {
      id: "inst-nila",
      name: "Nila Foods Export",
      business: "Frozen-food exporter",
      mandate_type: "indian_b2b_lead_finder",
      ring: "observe",
      trust_score: 64,
      state: "live",
      health: "amber",
      owner: "Ops / Shivalik",
      monthly_net: 520,
      facts: [
        {
          id: "fact-nila-1",
          label: "Primary ICP",
          value: "Middle East importers with Indian frozen-snack catalogs",
          confidence: 0.71,
          provenance: "run-170/exa-search",
          source: "Exa",
          committed_at: "2026-06-18T08:22:00+05:30",
        },
        {
          id: "fact-nila-2",
          label: "Approval policy",
          value: "Draft-only email, no send action without manager approval",
          confidence: 1,
          provenance: "policy/sender-of-record",
          source: "Kernel policy",
          committed_at: "2026-06-18T08:24:20+05:30",
        },
      ],
      ring_history: [
        {
          at: "2026-06-17T18:40:00+05:30",
          ring: "observe",
          actor: "operator",
          reason: "first export-market batch still under review",
        },
      ],
      trust_history: [
        { label: "source match", score: 66, delta: 1 },
        { label: "draft quality", score: 59, delta: -3 },
        { label: "manual corrections", score: 78, delta: 4 },
      ],
      threads: [
        {
          id: "thread-nila-1",
          channel: "email",
          subject: "Importer list cleanup",
          state: "manual correction",
          updated_at: "2026-06-18T08:18:00+05:30",
        },
      ],
      pnl: {
        revenue: 750,
        cost: 230,
        margin: 520,
      },
    },
    {
      id: "inst-aster",
      name: "Aster Diagnostics",
      business: "Regional diagnostics chain",
      mandate_type: "indian_b2b_lead_finder",
      ring: "assist",
      trust_score: 74,
      state: "parked",
      health: "green",
      owner: "Ops / Mrigesh",
      monthly_net: 400,
      facts: [
        {
          id: "fact-aster-1",
          label: "Primary ICP",
          value: "HR teams at 200-800 employee manufacturers near Pune",
          confidence: 0.79,
          provenance: "run-168/firecrawl-directory",
          source: "Firecrawl",
          committed_at: "2026-06-17T21:12:00+05:30",
        },
      ],
      ring_history: [
        {
          at: "2026-06-17T16:30:00+05:30",
          ring: "observe",
          actor: "operator",
          reason: "pilot created",
        },
        {
          at: "2026-06-17T22:15:00+05:30",
          ring: "assist",
          actor: "operator",
          reason: "approved draft-only path",
        },
      ],
      trust_history: [
        { label: "source match", score: 80, delta: 4 },
        { label: "draft quality", score: 70, delta: 8 },
        { label: "manual corrections", score: 73, delta: 0 },
      ],
      threads: [
        {
          id: "thread-aster-1",
          channel: "manual",
          subject: "Paused for customer ICP confirmation",
          state: "parked",
          updated_at: "2026-06-18T07:02:00+05:30",
        },
      ],
      pnl: {
        revenue: 620,
        cost: 220,
        margin: 400,
      },
    },
  ],
  runs: [
    {
      id: "run-172",
      instance_id: "inst-kaveri",
      title: "Gujarat plant maintenance leads",
      state: "waiting_approval",
      syscall: "lead_research_batch",
      ring: "assist",
      started_at: "2026-06-18T08:34:00+05:30",
      updated_at: "2026-06-18T08:55:00+05:30",
      ledger_commits: 11,
      cost: 7.4,
      expected_value: 430,
      progress: 82,
      trace: [
        {
          id: "trace-172-1",
          at: "2026-06-18T08:34:12+05:30",
          kind: "syscall",
          title: "Intent committed",
          detail: "lead_research_batch for Gujarat food-processing plants",
          actor: "mandate/lead-finder",
          confidence: 1,
        },
        {
          id: "trace-172-2",
          at: "2026-06-18T08:37:40+05:30",
          kind: "adapter",
          title: "Firecrawl evidence attached",
          detail: "12 source pages captured with provenance stamps",
          actor: "gateway/firecrawl",
          confidence: 0.86,
        },
        {
          id: "trace-172-3",
          at: "2026-06-18T08:51:20+05:30",
          kind: "draft",
          title: "Email draft prepared",
          detail: "Draft-only path, sent:false, approval required",
          actor: "adapter/draft_email",
          confidence: 0.78,
        },
      ],
    },
    {
      id: "run-171",
      instance_id: "inst-kaveri",
      title: "Owner ICP correction sweep",
      state: "active",
      syscall: "read_url",
      ring: "assist",
      started_at: "2026-06-18T08:10:00+05:30",
      updated_at: "2026-06-18T08:49:00+05:30",
      ledger_commits: 7,
      cost: 2.1,
      expected_value: 120,
      progress: 64,
      trace: [
        {
          id: "trace-171-1",
          at: "2026-06-18T08:10:40+05:30",
          kind: "fact",
          title: "Owner correction loaded",
          detail: "Exclude packaging-only plants from ICP",
          actor: "manager",
          confidence: 1,
        },
      ],
    },
    {
      id: "run-170",
      instance_id: "inst-nila",
      title: "Middle East importer research",
      state: "active",
      syscall: "lead_research_batch",
      ring: "observe",
      started_at: "2026-06-18T08:02:00+05:30",
      updated_at: "2026-06-18T08:46:00+05:30",
      ledger_commits: 9,
      cost: 9.8,
      expected_value: 510,
      progress: 58,
      trace: [
        {
          id: "trace-170-1",
          at: "2026-06-18T08:08:10+05:30",
          kind: "adapter",
          title: "Exa search returned importer candidates",
          detail: "8 leads retained, 4 rejected for weak source match",
          actor: "gateway/exa",
          confidence: 0.71,
        },
      ],
    },
    {
      id: "run-168",
      instance_id: "inst-aster",
      title: "Pune employer list",
      state: "parked",
      syscall: "queue_manual_action",
      ring: "assist",
      started_at: "2026-06-17T20:20:00+05:30",
      updated_at: "2026-06-18T07:02:00+05:30",
      ledger_commits: 14,
      cost: 5.9,
      expected_value: 260,
      progress: 45,
      trace: [
        {
          id: "trace-168-1",
          at: "2026-06-18T07:02:00+05:30",
          kind: "human-task",
          title: "Parked for customer confirmation",
          detail: "Awaiting ICP change before more research spend",
          actor: "human-tail",
          confidence: 1,
        },
      ],
    },
  ],
  mandateTypes: [
    {
      id: "indian_b2b_lead_finder",
      title: "Indian B2B Lead Finder",
      stage: "Phase 1 live",
      ring_floor: "observe",
      unit_economics: "research batch -> approved draft -> outcome mark",
      commands: ["lead_research_batch", "read_url", "draft_email", "mark_outcome"],
      status: "ready",
    },
    {
      id: "invoice_reconciliation_desk",
      title: "Invoice Reconciliation Desk",
      stage: "parked",
      ring_floor: "manual",
      unit_economics: "blocked by money/workflow adapter scope",
      commands: ["queue_manual_action"],
      status: "gap",
      gap_id: "gap-create-instance",
    },
    {
      id: "whatsapp_followup",
      title: "WhatsApp Follow-up Agent",
      stage: "out of Phase 1",
      ring_floor: "locked",
      unit_economics: "not permitted in current adapter scope",
      commands: [],
      status: "locked",
      gap_id: "gap-whatsapp",
    },
  ],
  journal: [
    {
      id: "j-9001",
      at: "2026-06-18T08:55:30+05:30",
      kind: "approval",
      instance_id: "inst-kaveri",
      run_id: "run-172",
      actor: "adapter/draft_email",
      title: "Approval packet queued",
      detail: "Draft-only outreach requires manager approval",
      source: "kernel-journal",
    },
    {
      id: "j-9000",
      at: "2026-06-18T08:54:30+05:30",
      kind: "fact",
      instance_id: "inst-kaveri",
      run_id: "run-172",
      actor: "gateway/firecrawl",
      title: "Company source committed",
      detail: "New lead evidence stamped with source URL",
      source: "mongo/facts",
    },
    {
      id: "j-8998",
      at: "2026-06-18T08:49:00+05:30",
      kind: "trace",
      instance_id: "inst-kaveri",
      run_id: "run-171",
      actor: "mandate/lead-finder",
      title: "ICP correction applied",
      detail: "Packaging-only plants filtered from next batch",
      source: "kernel-journal",
    },
    {
      id: "j-8994",
      at: "2026-06-18T08:46:00+05:30",
      kind: "adapter",
      instance_id: "inst-nila",
      run_id: "run-170",
      actor: "gateway/exa",
      title: "Importer candidate list returned",
      detail: "8 retained candidates, all read-class traces recorded",
      source: "kernel-journal",
    },
    {
      id: "j-8980",
      at: "2026-06-18T07:02:00+05:30",
      kind: "human-task",
      instance_id: "inst-aster",
      run_id: "run-168",
      actor: "human-tail",
      title: "Run parked",
      detail: "Customer ICP confirmation required before spending more",
      source: "manual-queue",
    },
  ],
  capabilities: [
    {
      id: "cap-lead-research",
      title: "Lead research batch",
      syscall: "lead_research_batch",
      maturity: "live",
      health: "healthy",
      queue_volume: 2,
      credential_boundary: "gateway-injected",
      terminal_fallback: true,
    },
    {
      id: "cap-read-url",
      title: "Read URL",
      syscall: "read_url",
      maturity: "api",
      health: "healthy",
      queue_volume: 0,
      credential_boundary: "harness-native read",
      terminal_fallback: true,
    },
    {
      id: "cap-draft-email",
      title: "Draft email",
      syscall: "draft_email",
      maturity: "api",
      health: "healthy",
      queue_volume: 3,
      credential_boundary: "draft-only sent:false",
      terminal_fallback: true,
    },
    {
      id: "cap-manual-action",
      title: "Human task tail",
      syscall: "queue_manual_action",
      maturity: "manual",
      health: "queued",
      queue_volume: 5,
      credential_boundary: "operator-owned",
      terminal_fallback: true,
    },
    {
      id: "cap-mark-outcome",
      title: "Mark outcome",
      syscall: "mark_outcome",
      maturity: "api",
      health: "healthy",
      queue_volume: 1,
      credential_boundary: "journal-only",
      terminal_fallback: true,
    },
  ],
  evalCases: [
    {
      id: "eval-001",
      pack: "indian_b2b_leads_v1",
      origin: "synthetic",
      title: "Plastic plant lead scrape",
      status: "graded",
      score: 0.74,
      promotion: "blocked",
    },
    {
      id: "eval-002",
      pack: "indian_b2b_leads_v1",
      origin: "synthetic",
      title: "Food exporter false-positive rejection",
      status: "graded",
      score: 0.81,
      promotion: "blocked",
    },
    {
      id: "eval-003",
      pack: "indian_b2b_leads_v1",
      origin: "human_reviewed",
      title: "Kaveri approved lead batch",
      status: "passed",
      score: 0.88,
      promotion: "eligible",
    },
  ],
  manualQueue: [
    {
      id: "task-approve-172",
      instance_id: "inst-kaveri",
      run_id: "run-172",
      title: "Approve Kaveri draft batch",
      drafted_effect: "Commit 12 leads, attach Firecrawl evidence, keep outreach as draft-only with sent:false.",
      priority: "high",
      age_minutes: 11,
      trace: [
        "lead_research_batch intent committed",
        "gateway injected Firecrawl credential",
        "draft_email produced sent:false artifact",
      ],
      status: "open",
    },
    {
      id: "task-clean-nila",
      instance_id: "inst-nila",
      run_id: "run-170",
      title: "Review importer source mismatch",
      drafted_effect: "Reject weak importer matches and settle corrected ICP note.",
      priority: "normal",
      age_minutes: 38,
      trace: ["Exa candidates returned", "4 weak-source leads flagged", "human-task tail reached"],
      status: "open",
    },
    {
      id: "task-aster-park",
      instance_id: "inst-aster",
      run_id: "run-168",
      title: "Confirm parked ICP",
      drafted_effect: "Keep run parked until customer confirms employer-size constraint.",
      priority: "low",
      age_minutes: 146,
      trace: ["queue_manual_action invoked", "run parked", "no unimplemented fallback"],
      status: "open",
    },
  ],
  coreGaps: [
    {
      id: "gap-create-instance",
      title: "Create command unavailable",
      detail: "The dashboard can stage the create request, but Phase 1 exposes no instantiate command endpoint yet.",
    },
    {
      id: "gap-edit-reject",
      title: "Approval edit/reject command unavailable",
      detail: "Approve is wired. Edit and reject remain explicit core gaps until the command API supports them.",
    },
    {
      id: "gap-whatsapp",
      title: "Channel outside Phase 1",
      detail: "WhatsApp, money, voice, and browser adapters are not part of the current lead-finder lane.",
    },
  ],
};

export const getFixtureInstance = (instanceId: string) =>
  fixtureDashboardData.instances.find((instance) => instance.id === instanceId) ??
  fixtureDashboardData.instances[0];

export const getFixtureRun = (runId: string) =>
  fixtureDashboardData.runs.find((run) => run.id === runId) ?? fixtureDashboardData.runs[0];

export const getCoreGap = (gapId: string) =>
  fixtureDashboardData.coreGaps.find((gap) => gap.id === gapId) ?? fixtureDashboardData.coreGaps[0];
