import type { DashboardData, MandateType, FacultyLibraryEntry } from "./types";

const RICH_MANDATE_TYPES: MandateType[] = [
  {
    id: "lead-finder",
    title: "Lead Finder",
    type_ref: "lead-finder@0.3.1",
    stage: "0.3.1",
    ring_floor: "L1",
    unit_economics:
      "research_batch → approved draft → reply watch → settlement. ~₹180 per qualified lead at L1.",
    commands: [
      "research_batch",
      "score_lead",
      "draft_email",
      "send_email",
      "mark_outcome",
    ],
    status: "ready",
    description:
      "B2B lead-finder mandate — researches prospects, scores them against an ICP, drafts outreach, and (after approval) sends as the per-instance sender. The §1 reference implementation: every other mandate type reuses its faculty set.",
    instances_count: 3,
    versions: [
      {
        version: "0.3.1",
        released_at: "2026-06-18T08:54:30+05:30",
        status: "live",
        changelog:
          "L1 trust rung wired end-to-end; send_email live on SMTP; reply-watch maturation stub (awaiting 72h real reply data).",
      },
      {
        version: "0.3.0",
        released_at: "2026-06-10T12:00:00+05:30",
        status: "live",
        changelog: "L0 observe rung promoted from canary; Phase-1 reference build.",
      },
      {
        version: "0.2.4",
        released_at: "2026-05-28T09:15:00+05:30",
        status: "deprecated",
        changelog: "Pre-send-loop — research + draft only; superseded by 0.3.0.",
      },
    ],
    charter: {
      goal: "Deliver one qualified lead (name + ICP-fit evidence + drafted outreach) per run.",
      preconditions: [
        "Customer has set sender_identity (per-instance outbound address).",
        "ICP target is non-empty (industry + location + count).",
      ],
      pathconditions: [
        "Every fact carries provenance (run_id + evidence).",
        "Drafts require approval before send_email rung (L0/L1).",
      ],
      postconditions: [
        "Approved lead fact committed to heap at ≥0.6 confidence.",
        "Trust +1 on success / −1 on failure (settlement).",
      ],
      constraints: [
        "No raw fact crosses customers (invariant #3).",
        "send_email uses the instance's sender identity, never a shared global (invariant #8).",
      ],
      target: { industry: "industrial_pumps", location: "india", count: 50 },
    },
    faculties: [
      {
        faculty_name: "research_batch",
        faculty_version: "1.4.0",
        harness: "exa_search",
        model: "exa-pro",
        budget: 0.04,
        description:
          "Pulls a batch of candidate companies + decision-makers from Exa. ICP-targeted, paginated.",
      },
      {
        faculty_name: "score_lead",
        faculty_version: "1.1.0",
        harness: "judge",
        model: "haiku-4",
        budget: 0.005,
        description: "Grades each candidate against the ICP target on the lead_quality rubric.",
      },
      {
        faculty_name: "draft_email",
        faculty_version: "0.9.2",
        harness: "sim",
        model: "sonnet-4",
        budget: 0.02,
        description: "Drafts a personalized first-touch email. Draft-only; never sends without approval.",
      },
      {
        faculty_name: "send_email",
        faculty_version: "2.1.0",
        harness: "smtp",
        model: "—",
        budget: null,
        description:
          "SMTP transport (Gmail App Password). Idempotent on draft id; uses the per-instance sender_identity.",
      },
      {
        faculty_name: "mark_outcome",
        faculty_version: "0.6.0",
        harness: "human_task",
        model: "—",
        budget: null,
        description: "Owner confirms reply / meeting / no-response; trust deltas applied at settlement.",
      },
    ],
    domain_pack: {
      name: "b2b_saas_india",
      version: "1.2.0",
      vertical: "B2B SaaS, India",
    },
    verification: {
      ladder: [
        { rung: "rules", present: true },
        { rung: "judge", present: true },
        { rung: "human", present: true },
        { rung: "reality", present: true },
      ],
      rules: ["icp_non_empty", "sender_identity_set", "evidence_link_present"],
      rubrics: ["lead_quality"],
    },
    settlement: {
      fact_commit_confidence: 0.6,
      trust_on_success: 1,
      trust_on_failure: -1,
      watch_window_hours: 72,
      spawn_rules: [
        {
          on_condition: "lead_qualified_and_approved",
          child_type_ref: "followup-sequence@0.1.0",
        },
      ],
      billing_per_run: 0.18,
    },
    gym_ref: {
      name: "lead_finder_gym",
      status: "active",
      cases_count: 47,
    },
    execution: {
      routing: [
        { faculty_name: "research_batch", harness: "exa_search", model: "exa-pro", budget: 0.04 },
        { faculty_name: "score_lead", harness: "judge", model: "haiku-4", budget: 0.005 },
        { faculty_name: "draft_email", harness: "sim", model: "sonnet-4", budget: 0.02 },
        { faculty_name: "send_email", harness: "smtp", model: "—", budget: null },
        { faculty_name: "mark_outcome", harness: "human_task", model: "—", budget: null },
      ],
    },
    service_ports: ["qualified_leads"],
  },
  {
    id: "creator",
    title: "Creator",
    type_ref: "creator@0.1.0",
    stage: "0.1.0",
    ring_floor: "L0",
    unit_economics:
      "draft-only rung at canary → catalog write once promoted. Produces candidate MandateTypes, never runs them itself.",
    commands: [
      "draft_candidate_type",
      "compile_candidate",
      "promote_candidate",
    ],
    status: "canary",
    description:
      "Creator mandate — drafts new mandate types and gates them on the same PromotionGate as the swarm. Draft-only at canary rung (L0); promotion to write rung is C8 / Phase-8 work.",
    instances_count: 1,
    versions: [
      {
        version: "0.1.0",
        released_at: "2026-06-15T08:00:00+05:30",
        status: "canary",
        changelog:
          "Draft-only rung. Promotion to catalog write is gated on synthetic+human+real evidence per PromotionGate.",
      },
    ],
    charter: {
      goal: "Produce a candidate MandateType draft that survives PromotionGate.",
      preconditions: ["Operator has set the target vertical + faculties to bind."],
      pathconditions: ["Drafts are emitted only at L0 (canary) — never write to live catalog yet."],
      postconditions: ["Candidate entry lands in catalog as `origin=creator` stamp."],
      constraints: [
        "No synthetic-only case may promote a customer-facing version (invariant #7).",
      ],
      target: { vertical: "ops_research", faculties: ["draft_candidate_type"] },
    },
    faculties: [
      {
        faculty_name: "draft_candidate_type",
        faculty_version: "0.4.0",
        harness: "sim",
        model: "opus-4",
        budget: 0.18,
        description: "Emits a candidate MandateType draft from a target + faculty-set prompt.",
      },
      {
        faculty_name: "compile_candidate",
        faculty_version: "0.2.0",
        harness: "judge",
        model: "sonnet-4",
        budget: 0.05,
        description: "GEPA-style compile: refines a candidate against the gym corpus.",
      },
      {
        faculty_name: "promote_candidate",
        faculty_version: "0.1.0",
        harness: "human_task",
        model: "—",
        budget: null,
        description:
          "Human-in-the-loop promotion gate; only fires when PromotionGate allows + human approves.",
      },
    ],
    domain_pack: {
      name: "ops_research",
      version: "0.1.0",
      vertical: "Meta-mandate authoring",
    },
    verification: {
      ladder: [
        { rung: "rules", present: true },
        { rung: "judge", present: true },
        { rung: "human", present: true },
        { rung: "reality", present: false },
      ],
      rules: ["candidate_has_charter", "candidate_faculties_resolve"],
      rubrics: ["candidate_quality"],
    },
    settlement: {
      fact_commit_confidence: 0.7,
      trust_on_success: 2,
      trust_on_failure: -2,
      watch_window_hours: 168,
      spawn_rules: [],
      billing_per_run: 0.0,
    },
    gym_ref: {
      name: "creator_gym",
      status: "dormant",
      cases_count: 12,
    },
    execution: {
      routing: [
        { faculty_name: "draft_candidate_type", harness: "sim", model: "opus-4", budget: 0.18 },
        { faculty_name: "compile_candidate", harness: "judge", model: "sonnet-4", budget: 0.05 },
        { faculty_name: "promote_candidate", harness: "human_task", model: "—", budget: null },
      ],
    },
    service_ports: [],
  },
  {
    id: "invoice-reconciliation-desk",
    title: "Invoice Reconciliation Desk",
    type_ref: "invoice-reconciliation-desk@0.0.1",
    stage: "0.0.1",
    ring_floor: "manual",
    unit_economics:
      "Blocked by Phase-1 scope: money adapters are explicitly excluded (invariant #6). Stage as parked.",
    commands: ["queue_manual_action"],
    status: "gap",
    gap_id: "gap-money-adapter",
    description:
      "Reconciles inbound invoices against ledger entries. Parked because money adapters are not part of Phase 1 (BLUEPRINT invariant #6 — money is API-only, idempotent, never LLM/browser).",
    instances_count: 0,
    versions: [
      {
        version: "0.0.1",
        released_at: "2026-06-01T00:00:00+05:30",
        status: "draft",
        changelog: "Design draft. Money adapters out of Phase 1 scope; see invariant #6.",
      },
    ],
    charter: {
      goal: "Match inbound invoice lines to ledger entries; flag mismatches for human review.",
      preconditions: [],
      pathconditions: [],
      postconditions: [],
      constraints: ["Money adapters are not part of Phase 1 — invariant #6."],
      target: {},
    },
    faculties: [
      {
        faculty_name: "queue_manual_action",
        faculty_version: "0.1.0",
        harness: "human_task",
        model: "—",
        budget: null,
        description: "Parks an invoice reconciliation task for human owner review.",
      },
    ],
    domain_pack: { name: "core", version: "0.1.0", vertical: "Finance ops" },
    verification: {
      ladder: [
        { rung: "rules", present: false },
        { rung: "judge", present: false },
        { rung: "human", present: true },
        { rung: "reality", present: false },
      ],
      rules: [],
      rubrics: [],
    },
    settlement: {
      fact_commit_confidence: 0.5,
      trust_on_success: 0,
      trust_on_failure: 0,
      watch_window_hours: 24,
      spawn_rules: [],
      billing_per_run: null,
    },
    gym_ref: null,
    execution: {
      routing: [
        {
          faculty_name: "queue_manual_action",
          harness: "human_task",
          model: "—",
          budget: null,
        },
      ],
    },
    service_ports: [],
  },
  {
    id: "whatsapp-followup",
    title: "WhatsApp Follow-up Agent",
    type_ref: "whatsapp-followup@0.0.0",
    stage: "0.0.0",
    ring_floor: "locked",
    unit_economics: "Locked — WhatsApp channel is Phase-2 (not Phase 1).",
    commands: [],
    status: "locked",
    gap_id: "gap-whatsapp-adapter",
    description:
      "WhatsApp follow-up agent. Locked because the WhatsApp adapter is Phase-2 work; per-instance sender identity + idempotency required before unlock.",
    instances_count: 0,
    versions: [],
    charter: {
      goal: "Send a WhatsApp follow-up 48h after email open.",
      preconditions: [],
      pathconditions: [],
      postconditions: [],
      constraints: ["WhatsApp adapter not in Phase 1 scope."],
      target: {},
    },
    faculties: [],
    domain_pack: { name: "core", version: "0.1.0", vertical: "Outbound channels" },
    verification: {
      ladder: [
        { rung: "rules", present: false },
        { rung: "judge", present: false },
        { rung: "human", present: false },
        { rung: "reality", present: false },
      ],
      rules: [],
      rubrics: [],
    },
    settlement: {
      fact_commit_confidence: 0.6,
      trust_on_success: 1,
      trust_on_failure: -1,
      watch_window_hours: 72,
      spawn_rules: [],
      billing_per_run: null,
    },
    gym_ref: null,
    execution: { routing: [] },
    service_ports: [],
  },
];

const FIXTURE_FACULTY_LIBRARY: FacultyLibraryEntry[] = [
  {
    name: "research_batch",
    version: "1.4.0",
    description: "Pulls a batch of candidate companies + decision-makers from Exa.",
    category: "research",
    used_by: ["Lead Finder"],
  },
  {
    name: "score_lead",
    version: "1.1.0",
    description: "Grades a candidate against an ICP target on the lead_quality rubric.",
    category: "analysis",
    used_by: ["Lead Finder"],
  },
  {
    name: "draft_email",
    version: "0.9.2",
    description: "Drafts a personalized first-touch email. Draft-only by default.",
    category: "content",
    used_by: ["Lead Finder"],
  },
  {
    name: "send_email",
    version: "2.1.0",
    description: "SMTP transport with per-instance sender identity + idempotency.",
    category: "outreach",
    used_by: ["Lead Finder"],
  },
  {
    name: "mark_outcome",
    version: "0.6.0",
    description: "Owner confirms reply / meeting / no-response; trust deltas applied.",
    category: "ops",
    used_by: ["Lead Finder"],
  },
  {
    name: "draft_candidate_type",
    version: "0.4.0",
    description: "Creator faculty — emits a candidate MandateType draft.",
    category: "content",
    used_by: ["Creator"],
  },
  {
    name: "compile_candidate",
    version: "0.2.0",
    description: "GEPA-style compile: refines a candidate against the gym corpus.",
    category: "analysis",
    used_by: ["Creator"],
  },
  {
    name: "promote_candidate",
    version: "0.1.0",
    description: "Human-in-the-loop promotion gate.",
    category: "ops",
    used_by: ["Creator"],
  },
  {
    name: "queue_manual_action",
    version: "0.1.0",
    description: "Parks a task for human owner review (terminal tail fallback).",
    category: "ops",
    used_by: ["Invoice Reconciliation Desk"],
  },
  {
    name: "watch_reply",
    version: "0.3.0",
    description: "Reply-watch maturation worker — promotes probation facts to verified.",
    category: "analysis",
    used_by: [],
  },
];

export const fixtureDashboardData: DashboardData = {
  health: {
    status: "fixture",
    service: "agentx-kernel-api",
    checked_at: "2026-06-18T09:00:00+05:30",
  },
  overview: {
    system_state: "live-dogfood",
    active_instances: 3,
    active_runs: 4,
    parked_runs: 2,
    approvals_waiting: 3,
    manual_queue_depth: 5,
    ledger_events_today: 47,
    automation_coverage: 0.68,
    monthly_net: 1840,
    gateway_health: "credential-boundary-enforced",
    ring_mix: {
      observe: 1,
      assist: 2,
      autopilot: 0,
    },
    last_commit_at: "2026-06-18T08:54:30+05:30",
  },
  instances: [
    {
      id: "inst-kaveri",
      name: "Kaveri Pumps",
      business: "Industrial pump distributor",
      mandate_type: "indian_b2b_lead_finder",
      ring: "assist",
      trust_score: 82,
      state: "live",
      health: "green",
      owner: "Ops / Mrigesh",
      monthly_net: 920,
      facts: [
        {
          id: "fact-kav-1",
          label: "Primary ICP",
          value: "Plant maintenance heads at food-processing units in Gujarat",
          confidence: 0.84,
          provenance: "run-172/firecrawl/company-page",
          source: "Firecrawl",
          committed_at: "2026-06-18T08:41:00+05:30",
        },
        {
          id: "fact-kav-2",
          label: "Sender of record",
          value: "sales@kaveripumps.example",
          confidence: 0.91,
          provenance: "manager-action-approve-29",
          source: "Manager approval",
          committed_at: "2026-06-18T08:45:12+05:30",
        },
        {
          id: "fact-kav-3",
          label: "Do-not-contact",
          value: "No WhatsApp or voice automation in Phase 1",
          confidence: 1,
          provenance: "policy/invariant-6",
          source: "Kernel policy",
          committed_at: "2026-06-18T08:52:03+05:30",
        },
      ],
      ring_history: [
        {
          at: "2026-06-17T19:20:00+05:30",
          ring: "observe",
          actor: "operator",
          reason: "new instance created",
        },
        {
          at: "2026-06-18T07:50:00+05:30",
          ring: "assist",
          actor: "operator",
          reason: "two human-reviewed lead batches passed",
        },
      ],
      trust_history: [
        { label: "source match", score: 88, delta: 6 },
        { label: "draft quality", score: 76, delta: 2 },
        { label: "manual corrections", score: 91, delta: 9 },
      ],
      threads: [
        {
          id: "thread-kav-1",
          channel: "email",
          subject: "Batch 12 draft outreach",
          state: "waiting approval",
          updated_at: "2026-06-18T08:46:00+05:30",
        },
        {
          id: "thread-kav-2",
          channel: "manual",
          subject: "ICP correction from owner",
          state: "settled",
          updated_at: "2026-06-18T07:30:00+05:30",
        },
      ],
      pnl: {
        revenue: 1200,
        cost: 280,
        margin: 920,
      },
    },
    {
      id: "inst-nila",
      name: "Nila Foods Export",
      business: "Frozen-food exporter",
      mandate_type: "indian_b2b_lead_finder",
      ring: "observe",
      trust_score: 64,
      state: "live",
      health: "amber",
      owner: "Ops / Shivalik",
      monthly_net: 520,
      facts: [
        {
          id: "fact-nila-1",
          label: "Primary ICP",
          value: "Middle East importers with Indian frozen-snack catalogs",
          confidence: 0.71,
          provenance: "run-170/exa-search",
          source: "Exa",
          committed_at: "2026-06-18T08:22:00+05:30",
        },
        {
          id: "fact-nila-2",
          label: "Approval policy",
          value: "Draft-only email, no send action without manager approval",
          confidence: 1,
          provenance: "policy/sender-of-record",
          source: "Kernel policy",
          committed_at: "2026-06-18T08:24:20+05:30",
        },
      ],
      ring_history: [
        {
          at: "2026-06-17T18:40:00+05:30",
          ring: "observe",
          actor: "operator",
          reason: "first export-market batch still under review",
        },
      ],
      trust_history: [
        { label: "source match", score: 66, delta: 1 },
        { label: "draft quality", score: 59, delta: -3 },
        { label: "manual corrections", score: 78, delta: 4 },
      ],
      threads: [
        {
          id: "thread-nila-1",
          channel: "email",
          subject: "Importer list cleanup",
          state: "manual correction",
          updated_at: "2026-06-18T08:18:00+05:30",
        },
      ],
      pnl: {
        revenue: 750,
        cost: 230,
        margin: 520,
      },
    },
    {
      id: "inst-aster",
      name: "Aster Diagnostics",
      business: "Regional diagnostics chain",
      mandate_type: "indian_b2b_lead_finder",
      ring: "assist",
      trust_score: 74,
      state: "parked",
      health: "green",
      owner: "Ops / Mrigesh",
      monthly_net: 400,
      facts: [
        {
          id: "fact-aster-1",
          label: "Primary ICP",
          value: "HR teams at 200-800 employee manufacturers near Pune",
          confidence: 0.79,
          provenance: "run-168/firecrawl-directory",
          source: "Firecrawl",
          committed_at: "2026-06-17T21:12:00+05:30",
        },
      ],
      ring_history: [
        {
          at: "2026-06-17T16:30:00+05:30",
          ring: "observe",
          actor: "operator",
          reason: "pilot created",
        },
        {
          at: "2026-06-17T22:15:00+05:30",
          ring: "assist",
          actor: "operator",
          reason: "approved draft-only path",
        },
      ],
      trust_history: [
        { label: "source match", score: 80, delta: 4 },
        { label: "draft quality", score: 70, delta: 8 },
        { label: "manual corrections", score: 73, delta: 0 },
      ],
      threads: [
        {
          id: "thread-aster-1",
          channel: "manual",
          subject: "Paused for customer ICP confirmation",
          state: "parked",
          updated_at: "2026-06-18T07:02:00+05:30",
        },
      ],
      pnl: {
        revenue: 620,
        cost: 220,
        margin: 400,
      },
    },
  ],
  runs: [
    {
      id: "run-172",
      instance_id: "inst-kaveri",
      title: "Gujarat plant maintenance leads",
      state: "waiting_approval",
      syscall: "lead_research_batch",
      ring: "assist",
      started_at: "2026-06-18T08:34:00+05:30",
      updated_at: "2026-06-18T08:55:00+05:30",
      ledger_commits: 11,
      cost: 7.4,
      expected_value: 430,
      progress: 82,
      trace: [
        {
          kind: "syscall",
          ts: "2026-06-18T08:34:12+05:30",
          actor: "mandate/lead-finder",
          summary: "Intent committed",
          event: { id: "trace-172-1", detail: "lead_research_batch for Gujarat food-processing plants", confidence: 1 },
        },
        {
          kind: "adapter",
          ts: "2026-06-18T08:37:40+05:30",
          actor: "gateway/firecrawl",
          summary: "Firecrawl evidence attached",
          event: { id: "trace-172-2", detail: "12 source pages captured with provenance stamps", confidence: 0.86 },
        },
        {
          kind: "draft",
          ts: "2026-06-18T08:51:20+05:30",
          actor: "adapter/draft_email",
          summary: "Email draft prepared",
          event: { id: "trace-172-3", detail: "Draft-only path, sent:false, approval required", confidence: 0.78 },
        },
      ],
    },
    {
      id: "run-171",
      instance_id: "inst-kaveri",
      title: "Owner ICP correction sweep",
      state: "active",
      syscall: "read_url",
      ring: "assist",
      started_at: "2026-06-18T08:10:00+05:30",
      updated_at: "2026-06-18T08:49:00+05:30",
      ledger_commits: 7,
      cost: 2.1,
      expected_value: 120,
      progress: 64,
      trace: [
        {
          kind: "fact",
          ts: "2026-06-18T08:10:40+05:30",
          actor: "manager",
          summary: "Owner correction loaded",
          event: { id: "trace-171-1", detail: "Exclude packaging-only plants from ICP", confidence: 1 },
        },
      ],
    },
    {
      id: "run-170",
      instance_id: "inst-nila",
      title: "Middle East importer research",
      state: "active",
      syscall: "lead_research_batch",
      ring: "observe",
      started_at: "2026-06-18T08:02:00+05:30",
      updated_at: "2026-06-18T08:46:00+05:30",
      ledger_commits: 9,
      cost: 9.8,
      expected_value: 510,
      progress: 58,
      trace: [
        {
          kind: "adapter",
          ts: "2026-06-18T08:08:10+05:30",
          actor: "gateway/exa",
          summary: "Exa search returned importer candidates",
          event: { id: "trace-170-1", detail: "8 leads retained, 4 rejected for weak source match", confidence: 0.71 },
        },
      ],
    },
    {
      id: "run-168",
      instance_id: "inst-aster",
      title: "Pune employer list",
      state: "parked",
      syscall: "queue_manual_action",
      ring: "assist",
      started_at: "2026-06-17T20:20:00+05:30",
      updated_at: "2026-06-18T07:02:00+05:30",
      ledger_commits: 14,
      cost: 5.9,
      expected_value: 260,
      progress: 45,
      trace: [
        {
          kind: "human-task",
          ts: "2026-06-18T07:02:00+05:30",
          actor: "human-tail",
          summary: "Parked for customer confirmation",
          event: { id: "trace-168-1", detail: "Awaiting ICP change before more research spend", confidence: 1 },
        },
      ],
    },
  ],
  mandateTypes: RICH_MANDATE_TYPES,
  facultyLibrary: FIXTURE_FACULTY_LIBRARY,
  journal: [
    {
      id: "j-9001",
      at: "2026-06-18T08:55:30+05:30",
      kind: "approval",
      instance_id: "inst-kaveri",
      run_id: "run-172",
      actor: "adapter/draft_email",
      title: "Approval packet queued",
      detail: "Draft-only outreach requires manager approval",
      source: "kernel-journal",
    },
    {
      id: "j-9000",
      at: "2026-06-18T08:54:30+05:30",
      kind: "fact",
      instance_id: "inst-kaveri",
      run_id: "run-172",
      actor: "gateway/firecrawl",
      title: "Company source committed",
      detail: "New lead evidence stamped with source URL",
      source: "mongo/facts",
    },
    {
      id: "j-8998",
      at: "2026-06-18T08:49:00+05:30",
      kind: "trace",
      instance_id: "inst-kaveri",
      run_id: "run-171",
      actor: "mandate/lead-finder",
      title: "ICP correction applied",
      detail: "Packaging-only plants filtered from next batch",
      source: "kernel-journal",
    },
    {
      id: "j-8994",
      at: "2026-06-18T08:46:00+05:30",
      kind: "adapter",
      instance_id: "inst-nila",
      run_id: "run-170",
      actor: "gateway/exa",
      title: "Importer candidate list returned",
      detail: "8 retained candidates, all read-class traces recorded",
      source: "kernel-journal",
    },
    {
      id: "j-8980",
      at: "2026-06-18T07:02:00+05:30",
      kind: "human-task",
      instance_id: "inst-aster",
      run_id: "run-168",
      actor: "human-tail",
      title: "Run parked",
      detail: "Customer ICP confirmation required before spending more",
      source: "manual-queue",
    },
  ],
  capabilities: [
    {
      id: "cap-lead-research",
      title: "Lead research batch",
      syscall: "lead_research_batch",
      maturity: "live",
      health: "healthy",
      queue_volume: 2,
      credential_boundary: "gateway-injected",
      terminal_fallback: true,
    },
    {
      id: "cap-read-url",
      title: "Read URL",
      syscall: "read_url",
      maturity: "api",
      health: "healthy",
      queue_volume: 0,
      credential_boundary: "harness-native read",
      terminal_fallback: true,
    },
    {
      id: "cap-draft-email",
      title: "Draft email",
      syscall: "draft_email",
      maturity: "api",
      health: "healthy",
      queue_volume: 3,
      credential_boundary: "draft-only sent:false",
      terminal_fallback: true,
    },
    {
      id: "cap-manual-action",
      title: "Human task tail",
      syscall: "queue_manual_action",
      maturity: "manual",
      health: "queued",
      queue_volume: 5,
      credential_boundary: "operator-owned",
      terminal_fallback: true,
    },
    {
      id: "cap-mark-outcome",
      title: "Mark outcome",
      syscall: "mark_outcome",
      maturity: "api",
      health: "healthy",
      queue_volume: 1,
      credential_boundary: "journal-only",
      terminal_fallback: true,
    },
  ],
  evalCases: [
    {
      id: "eval-001",
      pack: "indian_b2b_leads_v1",
      origin: "synthetic",
      title: "Plastic plant lead scrape",
      status: "graded",
      score: 0.74,
      promotion: "blocked",
    },
    {
      id: "eval-002",
      pack: "indian_b2b_leads_v1",
      origin: "synthetic",
      title: "Food exporter false-positive rejection",
      status: "graded",
      score: 0.81,
      promotion: "blocked",
    },
    {
      id: "eval-003",
      pack: "indian_b2b_leads_v1",
      origin: "human_reviewed",
      title: "Kaveri approved lead batch",
      status: "passed",
      score: 0.88,
      promotion: "eligible",
    },
  ],
  approvals: [
    {
      run_id: "run-172",
      reason: "draft_email requires L2; instance currently runs at L1",
      required_ring: "L2",
      seq: 17,
      instance_id: "inst-kaveri",
      drafted_effect: {
        syscall: "draft_email",
        args: {
          to: "owner@kaverifoods.example",
          subject: "Outreach: Kaveri Foods importer pipeline",
          body: "Draft only. Tailored to the dairy-exporter line.",
        },
        idempotency_key: "agentx_draft_run-172_5",
      },
      timeline: [
        {
          kind: "syscall_attempted",
          ts: "2026-06-18T08:51:20+05:30",
          actor: "kernel",
          summary: "syscall: draft_email",
          event: {},
        },
        {
          kind: "run_parked",
          ts: "2026-06-18T08:51:25+05:30",
          actor: "kernel",
          summary: "parked: draft_email requires L2",
          event: {},
        },
      ],
    },
  ],
  manualQueue: [
    {
      id: "task-approve-172",
      instance_id: "inst-kaveri",
      run_id: "run-172",
      title: "Approve Kaveri draft batch",
      drafted_effect: "Commit 12 leads, attach Firecrawl evidence, keep outreach as draft-only with sent:false.",
      priority: "high",
      age_minutes: 11,
      trace: [
        "lead_research_batch intent committed",
        "gateway injected Firecrawl credential",
        "draft_email produced sent:false artifact",
      ],
      status: "open",
    },
    {
      id: "task-clean-nila",
      instance_id: "inst-nila",
      run_id: "run-170",
      title: "Review importer source mismatch",
      drafted_effect: "Reject weak importer matches and settle corrected ICP note.",
      priority: "normal",
      age_minutes: 38,
      trace: ["Exa candidates returned", "4 weak-source leads flagged", "human-task tail reached"],
      status: "open",
    },
    {
      id: "task-aster-park",
      instance_id: "inst-aster",
      run_id: "run-168",
      title: "Confirm parked ICP",
      drafted_effect: "Keep run parked until customer confirms employer-size constraint.",
      priority: "low",
      age_minutes: 146,
      trace: ["queue_manual_action invoked", "run parked", "no unimplemented fallback"],
      status: "open",
    },
  ],
  coreGaps: [
    {
      id: "gap-create-instance",
      title: "Create command unavailable",
      detail: "The dashboard can stage the create request, but Phase 1 exposes no instantiate command endpoint yet.",
    },
    {
      id: "gap-edit-reject",
      title: "Approval edit/reject command unavailable",
      detail: "Approve is wired. Edit and reject remain explicit core gaps until the command API supports them.",
    },
    {
      id: "gap-whatsapp",
      title: "Channel outside Phase 1",
      detail: "WhatsApp, money, voice, and browser adapters are not part of the current lead-finder lane.",
    },
  ],
};

export const getFixtureInstance = (instanceId: string) =>
  fixtureDashboardData.instances.find((instance) => instance.id === instanceId) ??
  fixtureDashboardData.instances[0];

export const getFixtureRun = (runId: string) =>
  fixtureDashboardData.runs.find((run) => run.id === runId) ?? fixtureDashboardData.runs[0];

export const getCoreGap = (gapId: string) =>
  fixtureDashboardData.coreGaps.find((gap) => gap.id === gapId) ?? fixtureDashboardData.coreGaps[0];
